name: Scrape latest data
permissions:
  contents: write
on:
  push:
  workflow_dispatch:
  schedule:
     - cron:  '59 13 * * 6'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: actions/cache@v4
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install parkrun-to-sqlite datasette && datasette install datasette-publish-vercel
    - name: restart docker with smaller MTU
      run: |-
        temp=$(mktemp)
        jq '. + {"mtu": 1280 }'  < "/etc/docker/daemon.json" > "$temp"
        sudo mv "$temp" "/etc/docker/daemon.json"
        sudo  systemctl restart docker
        echo "restarted"
    - name: Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        args: " --exit-node=100.97.181.28 --exit-node-allow-lan-access=true"
    - name: build db
      run: |
        parkrun-to-sqlite 3173185 parkruns.db
    - name: Commit & push changes
      run: |
        git config user.email "parkrunauto@jamesst.one"
        git config user.name "Automatic update"
        git add .
        git commit -m "Automated park run update on $(date)"
        git push -u origin main
    - name: Deploy
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
       datasette publish vercel parkruns.db \
          --token $VERCEL_TOKEN \
          --project parkrun


